### PR TITLE
GH-84 initial docs module creation

### PR DESCRIPTION
**Pull request by olegz**

### CODE REVIEW

**Comment by olegz** [comment]
@dsyer @markfisher So for this one I started by basically copying contents of README (with minor modifications, primarily from Mark's blog) as initial version.

**Comment by dsyer** [comment]
Thanks Oleg. In most other spring cloud projects we auto generate the README to avoid duplication. Can you set that up the same way?

**Comment by olegz** [comment]
@dsyer  I've modeled this after Spring Cloud Stream, but now I see that some other projects have a bit different structure. Just to confirm is this one of them https://github.com/spring-cloud/spring-cloud-cli? It appears to be one that generates README.

**Comment by dsyer** [comment]
Spring Cloud Stream is actually probably the only exception.

**Comment by olegz** [comment]
Closing in favor of https://github.com/spring-cloud/spring-cloud-function/pull/89

**Pull request closed without merging**
