### PR TITLE
function-sample-azure cleanup

### PR DESCRIPTION
**Pull request by miller79**
Cleaned up pom to use java.version instead of the compiler.source and compiler.target
Added version properties for azure-functions-java-library and azure-functions-maven-plugin
Updated the properties to be the latest recommended from Azure Functions
Used stagingDirectory in maven-resources-plugin
Updated README.adoc to say port 7071 instead of 8080

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@miller79 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-function&pullRequestId=433)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-function&pullRequestId=433) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by olegz** [comment]
Unfortunately I have to rejected due to inactivity. When you get a chance to sign  `Contributor License Agreement!` feel free to resubmit.

**Comment by miller79** [comment]
Will do.  The CLA is going through my companies legal team so hoping to have it signed this week.  I will reopen then.

**Comment by pivotal-issuemaster** [comment]
@miller79 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-function&pullRequestId=433)!

**Comment by miller79** [comment]
@olegz The CLA is now signed if you want to reopen this PR.  I can also make another one if needed.

**Pull request merged**
