### PR TITLE
Fixed a bug where Kotlin Lambda was incorrectly converted to a consum…

### PR DESCRIPTION
**Pull request by dmittriy13**
Contribution for #699

Fixed a bug where Kotlin Lambda was incorrectly converted to a consumer function.

### CODE REVIEW

**Comment by olegz** [comment]
Thanks Dmitriy, will take a look at it shortly

**Comment by dmittriy13** [comment]
The build crashes(even in the main branch) with errors:
`[ERROR] Errors: 
[ERROR]   SpringBootStreamHandlerTests.functionBeanWithoutJacksonConfig:66 » IllegalState
[ERROR]   SpringBootStreamHandlerTests.functionFluxBeanNoCatalog:86 » IllegalState Faile...
[ERROR]   SpringBootStreamHandlerTests.functionNonFluxBeanNoCatalog:76 » IllegalState Fa...`

at the same time, when launched from the IDE - these tests pass without errors...

P.S. I didn't understand why, but I noticed that if you disable the CustomRuntimeEventLoopTest test, then the assembly is successful.

**Comment by olegz** [comment]
I will look, don't worry about that. We're a bit light on Kotlin, so contributions like this are important. I'll make sure the tests are fixed

**Comment by olegz** [comment]
@dmittriy13 It looks good and build passes locally with the lates changes, so not sure why it fails for you.
I am ready to merge it. 
One quick question. Do you mind adding your name to `@author` in `KotlinLambdaToFunctionAutoConfiguration`?

**Comment by dmittriy13** [comment]
I don't mind, I added the @author tag.
Thanks for your review!

**Comment by olegz** [comment]
Dmitry, thank you for your contribution. Hope for more. . . especially on Kotlin side. Also, don't hesitate suggesting new feature and/or enhancements is you see it

**Pull request closed without merging**
