### PR TITLE
Add additional documentation around AWS jar layout

### PR DESCRIPTION
**Pull request by Walliee**
- Add to note explain when resource transformers are needed
- Fix relative linking in the adapters directory

see #359

### CODE REVIEW

**Comment by olegz** [comment]
Thank you @Walliee 
I'll add your name to the authors when merge

**Comment by Walliee** [comment]
@olegz Looks like this got closed without a merge.

**Comment by olegz** [comment]
It is - https://github.com/spring-cloud/spring-cloud-function/commit/372a3ce49d82fda55a455e7f518b640ee96d0805

**Comment by Walliee** [comment]
Hmm.. you are right but I still don't see the changes in generated [readme.adoc](https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-adapters/spring-cloud-function-adapter-aws). Is that documentation generation done separately?

**Comment by olegz** [comment]
That is correct as I needed to fix a few links that were broken with your commit which are also processed for generation of the main docs. But I may have done a bit more than I need to. In any event I fixed it manually for now.

Thank you for contributing!

**Pull request closed without merging**
