### PR TITLE
Fix adapters page link

### PR DESCRIPTION
**Pull request by tMatSuZ**
I fixed the broken link of the document.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@tMatSuZ Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-function&pullRequestId=314)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-function&pullRequestId=314) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@tMatSuZ Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-function&pullRequestId=314)!

**Comment by olegz** [comment]
I am not sure they are broken - https://cloud.spring.io/spring-cloud-static/spring-cloud-function/2.1.0.M1/aws.html
What makes you think they are?

**Comment by tMatSuZ** [comment]
@olegz 
I'm sorry. I was misunderstood. Since the link was broken when checked on Github, the correction was performed. But that was an error. Please reject this pull request.

**Pull request closed without merging**
