### PR TITLE
Copy configuration from context ObjectMapper

### PR DESCRIPTION
**Pull request by lbilger**
This PR reverts the change from 8b66fd2 that caused some regressions and tries to solve the problem in a different way: it just copies the original ObjectMapper before modifying it.

This should solve #1158 and #1159.

### CODE REVIEW

**Comment by ElectroLutz** [comment]
@olegz this might be the better fix.

**Comment by olegz** [comment]
This is how it was before/originally and it created a problem which actually did no harm to s-c-function application, but caused an adverse effect in other frameworks present at runtime. Basically by doing this we are modifying the ObjectMapper provided by boot.
I'll keep the PR open to think some more about it

**Comment by lbilger** [comment]
Hi @olegz, there is a small but significant difference to how it was before: the call to `copy()` should create a copy of the provided ObjectMapper and only modify the copy, not the original one.

**Comment by olegz** [comment]
Sorry didn't notice that. Merging

**Comment by sonallux** [comment]
@olegz When will there be a new release of spring-cloud-function containing this fix? I can not find any planed release on [calendar.spring.io](https://calendar.spring.io).

**Pull request closed without merging**
