### PR TITLE
Custom object type conversion is failing, when it has "headers" inside payload #882

### PR DESCRIPTION
**Pull request by atyamlalithya**
This below step is removing the headers from payload instead of copying from it. We need the headers in the payload as is and should not be lost when passed to the spring cloud function.

### CODE REVIEW

**Comment by atyamlalithya** [comment]
@olegz  I made this change for the issue mentioned here 
https://github.com/spring-cloud/spring-cloud-function/issues/844
Please let me know if this doesn't clarify I will create a test and update it here.

**Comment by olegz** [comment]
@atyamlalithya I think i understand. That is because we're treating your custom Object as POJO, thus mapping it only to a payload/body. 
Can you please change your function to use Spring Message `org.springframework.messaging.Message`. It only has two fields, `getPayoad()` and `getHeaders()`.
```
public class MyFunction
    implements Function<Message, String> {
    @Override
    public String apply(Message input) {
    }
}
``` 
I am not saying this is a final solution (need to think), but I just wanted you to try as well as provide an acceptable workaround.

Let me know

**Comment by atyamlalithya** [comment]
Hi Oleg, Yes i know Message would help but we have a lot of lambdas that are already using our Pojos and we don't want to change that. Right now we are using our own handler that extends SpringBootStreamHandler instead of the generic functionInvoker to fix this , but we need this fix to migrate our lambda to Spring Native. I feel this is something that needs to be fixed in SCF code.
Please review the PR and let me know if that will fix this.

**Comment by atyamlalithya** [comment]
Thanks @olegz. This will help us a lot

**Comment by srunnoe** [comment]
Olegz,

I noticed that the AWSCompanionAutoConfiguration in not included in the spring.factories file. How is AWSTypesMessageConverter ever suppose to make its way into the path of execution?

**Pull request closed without merging**
