### PR TITLE
#519 checkstyle-validation at spring-cloud-function-adapter-gcp is fail

### PR DESCRIPTION
**Pull request by jianran**
polish the code to pass the checkstyle-validation at spring-cloud-function-adapter-gcp

### CODE REVIEW

**Comment by olegz** [comment]
@meltsufin please review this when you get a min. It also appears to have merge conflict after applying your PRs.

**Comment by meltsufin** [comment]
@jianran I'm not able to reproduce the issue tbh.
I just ran `/mvnw clean package -pl spring-cloud-function-adapters/spring-cloud-function-adapter-gcp` and I don't see any reported failures.

**Comment by jianran** [comment]
> @jianran I'm not able to reproduce the issue tbh.
> I just ran `/mvnw clean package -pl spring-cloud-function-adapters/spring-cloud-function-adapter-gcp` and I don't see any reported failures.

reproduce the issue on master; I reproduce the issue by your command such as /mvnw clean package - pl spring-cloud-function-adapters/spring-cloud-function-adapter-gcp .

the output like this:
[ERROR] /Users/jianran.tfh/workspace_os/spring-cloud-function/spring-cloud-function-adapters/spring-cloud-function-adapter-gcp/src/test/java/org/springframework/cloud/function/adapter/gcp/FunctionInvokerBackgroundTests.java:50:2: Missing a Javadoc comment. [JavadocVariable]
[ERROR] /Users/jianran.tfh/workspace_os/spring-cloud-function/spring-cloud-function-adapters/spring-cloud-function-adapter-gcp/src/test/java/org/springframework/cloud/function/adapter/gcp/integration/LocalServerTestSupport.java:54:1: Utility classes should not have a public or default constructor. [HideUtilityClassConstructor]
[ERROR] /Users/jianran.tfh/workspace_os/spring-cloud-function/spring-cloud-function-adapters/spring-cloud-function-adapter-gcp/src/test/java/org/springframework/cloud/function/adapter/gcp/integration/LocalServerTestSupport.java:64: First sentence should end with a period. [JavadocStyle]

**Comment by olegz** [comment]
This does not merge
```
spring-cloud-function@oleg$ git checkout pr/520
Branch 'pr/520' set up to track remote branch 'pr/520' from 'upstream'.
Switched to a new branch 'pr/520'
spring-cloud-function@oleg$ git rebase master
First, rewinding head to replay your work on top of it...
Applying: #489 the received data which Post Flux data to FunctionController is not same as the function apply
Using index info to reconstruct a base tree...
M	spring-cloud-function-samples/function-sample/pom.xml
M	spring-cloud-function-web/src/main/java/org/springframework/cloud/function/web/RequestProcessor.java
M	spring-cloud-function-web/src/main/java/org/springframework/cloud/function/web/flux/FunctionController.java
Falling back to patching base and 3-way merge...
```

**Comment by olegz** [comment]
No joy
```
spring-cloud-function@oleg$ git checkout pr/520
Branch 'pr/520' set up to track remote branch 'pr/520' from 'upstream'.
Switched to a new branch 'pr/520'
spring-cloud-function@oleg$ git rebase master
First, rewinding head to replay your work on top of it...
Applying: replay
Applying: #489 the received data which Post Flux data to FunctionController is not same as the function apply
Using index info to reconstruct a base tree...
M	spring-cloud-function-samples/function-sample/pom.xml
M	spring-cloud-function-web/src/main/java/org/springframework/cloud/function/web/RequestProcessor.java
M	spring-cloud-function-web/src/main/java/org/springframework/cloud/function/web/flux/FunctionController.java
Falling back to patching base and 3-way merge...
Auto-merging spring-cloud-function-web/src/main/java/org/springframework/cloud/function/web/flux/FunctionController.java
CONFLICT (content): Merge conflict in spring-cloud-function-web/src/main/java/org/springframework/cloud/function/web/flux/FunctionController.java
Auto-merging spring-cloud-function-web/src/main/java/org/springframework/cloud/function/web/RequestProcessor.java
CONFLICT (content): Merge conflict in spring-cloud-function-web/src/main/java/org/springframework/cloud/function/web/RequestProcessor.java
Auto-merging spring-cloud-function-samples/function-sample/pom.xml
error: Failed to merge in the changes.
```
Here is what your tree looks like:
```
6df5a037 (HEAD -> pr/520, upstream/pr/520) fixed
ddb2cb1f replay
d7411178 (upstream/master, origin/master, origin/HEAD, pr/527, master) Re-enable GCP sample test and fix mvn not found
17c3f185 (pr/518) Move Layout into adapter class
8ca1b45c Temporarily ignore GCF sample test
cbc41aec (pr/517) Add gcp adapter to dep mgmt
dc3fd039 Add Integration Test for GCP Sample
417e54e0 Add special handling for collections  NegotiatingMessageConverterWrapper
e761aa50 polishing
b9979d17 remove
46ced610 remove jib
57dcb71b fix
bbfa9015 version
c6eb23c3 jib
3e2864bf jib
a6f59bab Polish POM for function-sample-supplier-exporter
5aeb77a0 Add Supplier Exporter sample
07e4de71 Fix Message unwrapping condition
10e93506 Fix styles
69cac342 Remove references to compiler and task in dependency module
b13f67fd Change from warn to debug when function is not found
8503c391 Re-enable ignored tests
74e10c10 Bumping versions
c1d472de (pr/510) Change package `gcloud` to `gcp`
10b9e3d3 Removed dependency on org.json
5f3f0cf9 (pr/490) Polishing
719f3745 GH-489 the received data which Post Flux data to FunctionController is not same as the function apply
29dc59bb Add GCP Background Functions Unit Tests
```
and here is the current master
```
d7411178 (HEAD -> master, upstream/master, origin/master, origin/HEAD, pr/527) Re-enable GCP sample test and fix mvn not found
17c3f185 (pr/518) Move Layout into adapter class
8ca1b45c Temporarily ignore GCF sample test
cbc41aec (pr/517) Add gcp adapter to dep mgmt
dc3fd039 Add Integration Test for GCP Sample
417e54e0 Add special handling for collections  NegotiatingMessageConverterWrapper
a6f59bab Polish POM for function-sample-supplier-exporter
5aeb77a0 Add Supplier Exporter sample
07e4de71 Fix Message unwrapping condition
10e93506 Fix styles
69cac342 Remove references to compiler and task in dependency module
b13f67fd Change from warn to debug when function is not found
8503c391 Re-enable ignored tests
74e10c10 Bumping versions
c1d472de (pr/510) Change package `gcloud` to `gcp`
10b9e3d3 Removed dependency on org.json
5f3f0cf9 (pr/490) Polishing
719f3745 GH-489 the received data which Post Flux data to FunctionController is not same as the function apply
29dc59bb Add GCP Background Functions Unit Tests
```

**Comment by meltsufin** [comment]
@olegz Are you able to repro the checkstyle failures? What am I missing?

**Pull request closed without merging**
