### PR TITLE
Update the GCF runtime versions.

### LINKED ISSUE #642: Upgrade GCP dependencies
GCP adapter is still using alpha GCP function framework api. Can we upgrade this as follows.

`functions-framework-api` from `1.0.0-alpha-2-rc3` to `1.0.3`
`java-function-invoker` from `1.0.0-alpha-2-rc4` to `1.0.1`

If someone is not working, would be happy to take it up. Thanks.

### PR DESCRIPTION
**Pull request by dzou**
Upgrade the GCF dependencies.

Fixes #642.

cc/ @meltsufin

### CODE REVIEW

**Review by meltsufin — APPROVED** [review]

**Comment by olegz** [comment]
Oops. doesn't build on master

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project spring-cloud-function-adapter-gcp: Compilation failure
[ERROR] /Users/ozhurakousky/dev/repo/spring-cloud-function/spring-cloud-function-adapters/spring-cloud-function-adapter-gcp/src/main/java/org/springframework/cloud/function/adapter/gcp/FunctionInvoker.java:[24,34] cannot access com.google.cloud.functions.Context
[ERROR]   bad class file: /Users/ozhurakousky/.m2/repository/com/google/cloud/functions/functions-framework-api/1.0.3/functions-framework-api-1.0.3.jar(com/google/cloud/functions/Context.class)
[ERROR]     class file has wrong version 55.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 

```

**Comment by dzou** [comment]
Interesting. Seems like the Google Cloud Function framework is targeting java 11 and no longer supports Java 8. https://github.com/GoogleCloudPlatform/functions-framework-java/issues/55 

However it looks like the Spring Cloud Function CI runs on Java 8.

Hmm. @meltsufin @olegz -- Any thoughts on how to proceed? If you would let us, I would be open to contributing to the project's travis CI config to making testing possible.

**Comment by meltsufin** [comment]
Right, I think the adapter for GCP can only target Java 11+ at this point.
@olegz What are our options to move forward?

**Comment by olegz** [comment]
@meltsufin Unfortunately we can't fully migrate to newer Java until bot does, so we need to be Java 8 compatible

**Comment by dzou** [comment]
I see. I will ask around more and do some more research to see how we can make this work. Right now the position on making GCF java11-only seems fairly firm: https://github.com/GoogleCloudPlatform/functions-framework-java/issues/55#issuecomment-684073317

**Pull request closed without merging**
