### PR TITLE
Move package ...adapter.gcloud to ...adapter.gcp

### PR DESCRIPTION
**Pull request by meltsufin**

### CODE REVIEW

**Comment by olegz** [comment]
@meltsufin after merging the #502 this one has a merge conflict. Can you please fix it and push it?

**Comment by meltsufin** [comment]
@olegz Done. Please take another kook. Thanks!

**Comment by olegz** [comment]
I still can't merge it or rebase to current master. Can you please rebase it again with current master?

**Comment by olegz** [comment]
@meltsufin I was able to merge it but it's ugly (see below), so I am going to revert it.

Can you please modify and ensure that it can be merged to master with `--ff-only`
```
dc42135d (upstream/master, master) Merge pull request #504 from meltsufin/gcloud-to-gcp
8b0b3d35 (upstream/pr/504) Merge branch 'master' into gcloud-to-gcp
5f3f0cf9 (origin/master, origin/HEAD, pr/490) Polishing
719f3745 GH-489 the received data which Post Flux data to FunctionController is not same as the function apply
29dc59bb Add GCP Background Functions Unit Tests

```

**Pull request merged**
